name: Build and deploy Function App & Static Web App
on:  
  workflow_dispatch:

jobs: 
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: 'Azure Login'
        uses: 'azure/login@v1'
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: 'Run Azure CLI commands'
        id: get-swa-key
        run: |
          echo "DEPLOYKEY=$(az staticwebapp secrets list -n fhirwatch --query {properties.apiKey})" >> $GITHUB_OUTPUT
