name: Build and deploy Function App & Static Web App
on:  
  workflow_dispatch:
env:
  AZURE_SUBSCRIPTION_ID: '1c642d88-5042-4d19-9d49-49be6612a40f'
jobs: 
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: 'Azure Login'
        uses: 'azure/login@v1'
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: 'Run Azure CLI commands'
        id: get-swa-key
        run: |
          result=$(az staticwebapp secrets list -n fhirwatch | jq -r ".properties.apiKey")
          echo "APIKEY=$result" >> $GITHUB_OUTPUT
      - name: 'Test Output'
        run: |
          echo ${{ steps.get-swa-key.outputs.APIKEY }}
